project:
  type: website
  render:
    - Small Cetacean and Pinnipeds/2018-2023.qmd
 

website:
  title: "MSI Report - IN DEVELOPMENT"
  navbar:
    left:
      - file: Small Cetacean and Pinnipeds/2018-2023.qmd
        text: MSI- 2018-2023 draft


format:
  html:
    theme:
      - cosmo
      - assets/sar_theme.scss
    toc: true
