project:
  type: website
  render:
    - LargeWhales/pakicetus-stockC.qmd
 

website:
  title: "MSI Report - IN DEVELOPMENT"
  navbar:
    left:
      - file: LargeWhales/pakicetus-stockC.qmd
        text: MSI- 2018-2023 draft


format:
  html:
    theme:
      - cosmo
      - assets/sar_theme.scss
    toc: true
