project:
  type: website
  render:
    - SmallCetaceansAndPinnipeds/MSIsmalls.qmd
 

website:
  title: "MSI Report - IN DEVELOPMENT"
  navbar:
    left:
      - file: SmallCetaceansAndPinnipeds/MSIsmalls.qmd
        text: MSI- 2018-2023 draft


format:
  html:
    theme:
      - cosmo
      - assets/sar_theme.scss
    toc: true
